version: '3.8'

services:
  app:
    image: thefosk/kuma-demo
    ports:
      - "5000:5000"
      - "15000:15000"
    networks:
      - mesh_docker_kuma-network
    environment:
      - KUMA_DPP_ADDRESS=app:5000
    depends_on:
      - app-sidecar
      - redis

  app-sidecar:
    image: kong/kuma-dp:2.9.2
    command: ["run", "--cp-address=https://172.20.0.2:5678", "--dataplane-token-file=/etc/kuma/AppTokenfile", "--dataplane-file=/etc/kuma/config.yaml"]
    networks:
      - mesh_docker_kuma-network
    volumes:
      - ./config/AppTokenfile:/etc/kuma/AppTokenfile
      - ./config/dataplane-demo-app.yaml:/etc/kuma/config.yaml
    environment:
      - KUMA_DNS_ENVOY_DNS_PORT=15055
      - KUMA_APPLICATION_PROBE_PROXY_PORT=9001
      - KUMA_DNS_CORE_DNS_BINARY_PATH=coredns
      - KUMA_CONTROL_PLANE_URL=https://172.20.0.2:5678
      - KUMA_DNS_CORE_DNS_PORT=15053
      - REDIS_SERVICE_PORT=6379
      - REDIS_SERVICE_HOST=127.0.0.2
      - DEMO_APP_SERVICE_HOST=10.99.137.194
      - DEMO_APP_SERVICE_PORT=5000
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      -  mesh_docker_kuma-network
    depends_on:
      - redis-sidecar

  redis-sidecar:
    image: kong/kuma-dp:2.9.2
    command: ["run", "--cp-address=https://172.20.0.2:5678", "--dataplane-token-file=/etc/kuma/redisTokenFile", "--dataplane-file=/etc/kuma/config.yaml"]
    networks:
      -  mesh_docker_kuma-network
    volumes:
      - ./config/redisTokenFile:/etc/kuma/redisTokenFile
      - ./config/dataplane-redis.yaml:/etc/kuma/config.yaml
    environment:
      - KUMA_CONTROL_PLANE_URL=https://172.20.0.2:5678
      - KUMA_APPLICATION_PROBE_PROXY_PORT=9001
      - KUMA_DNS_CORE_DNS_BINARY_PATH=coredns
      - REDIS_PORT_6379_TCP_PORT=6379
      - REDIS_PORT=tcp://10.111.223.105:6379
      - REDIS_SERVICE_HOST=10.111.223.105
      - REDIS_PORT_6379_TCP_ADDR=10.111.223.105
      - DEMO_APP_SERVICE_PORT=5000
      - DEMO_APP_PORT_5000_TCP=tcp://10.99.137.194:5000
      - REDIS_SERVICE_PORT=6379
      - REDIS_PORT_6379_TCP=tcp://10.111.223.105:6379
      - REDIS_PORT_6379_TCP_PROTO=tcp

networks:
   mesh_docker_kuma-network:
    driver: bridge
    external: true